# use base node image
FROM node:argon

# Add package.json
ADD package.json /app/package.json

# Set working dir 
WORKDIR /app

# Install dependencies
RUN npm install

# Start node server
CMD ["npm", "start"]
